import React, { useState, useRef } from "react";
import "./Dashboard.css";

function Dashboard() {
  const [image, setImage] = useState(null);
  const [imagePreview, setImagePreview] = useState(null);
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [dragActive, setDragActive] = useState(false);
  const inputRef = useRef(null);

  const handleFile = (file) => {
    if (file && file.type.startsWith("image/")) {
      setImage(file);
      const reader = new FileReader();
      reader.onloadend = () => {
        setImagePreview(reader.result);
      };
      reader.readAsDataURL(file);
    } else {
      alert("Please upload a valid image file.");
    }
  };

  const handleDrag = (e) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") {
      setDragActive(true);
    } else if (e.type === "dragleave") {
      setDragActive(false);
    }
  };

  const handleDrop = (e) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      handleFile(e.dataTransfer.files[0]);
    }
  };

  const handleChange = (e) => {
    e.preventDefault();
    if (e.target.files && e.target.files[0]) {
      handleFile(e.target.files[0]);
    }
  };

  const onButtonClick = () => {
    inputRef.current.click();
  };

  const handlePredict = async () => {
    if (!image) return alert("Please upload a CXR image first!");

    setLoading(true);
    const fd = new FormData();
    fd.append("image", image);

    try {
      const res = await fetch("http://127.0.0.1:8000/api/predict", {
        method: "POST",
        body: fd,
      });
      const data = await res.json();
      setResult(data);
    } catch (err) {
      alert("Error connecting to backend: " + err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="dashboard-container">
      <h1 className="dashboard-title">🫁 TB Chest X-Ray Classifier</h1>

      <div className="upload-section">
        <div
          className={`drag-drop-area ${dragActive ? "drag-active" : ""}`}
          onDragEnter={handleDrag}
          onDragLeave={handleDrag}
          onDragOver={handleDrag}
          onDrop={handleDrop}
        >
          <input
            ref={inputRef}
            type="file"
            accept="image/*"
            onChange={handleChange}
            className="file-input"
          />
          <p>Drag & Drop your Chest X-Ray image here or</p>
          <button className="upload-button" onClick={onButtonClick}>Browse Files</button>
          {imagePreview && (
            <button className="clear-button" onClick={() => {
              setImage(null);
              setImagePreview(null);
              setResult(null);
            }}>Clear Image</button>
          )}
        </div>

        {imagePreview && (
          <div className="image-preview">
            <h3>Selected Image:</h3>
            <img src={imagePreview} alt="Preview" className="preview-image" />
          </div>
        )}

        <button onClick={handlePredict} disabled={loading || !image} className="predict-button">
          {loading ? "Processing..." : "Run Prediction"}
        </button>
      </div>

      {result && result.classification && (
        <div className="results-section">
          <h2 className="results-title">
            Prediction: <span className={`prediction-label ${result.classification.label.toLowerCase()}`}>{result.classification.label}</span>
            <br />
            Confidence: <span className="confidence-score">{(result.classification.confidence * 100).toFixed(2)}%</span>
          </h2>
          <p className="results-description">Below are the visual insights generated by the model:</p>

          <div className="image-display-grid">
            <div className="image-display-block">
              <h3>Original X-ray</h3>
              <img
                src={`data:image/png;base64,${result.original_image}`}
                alt="Original X-ray"
                className="result-image"
              />
            </div>

            <div className="image-display-block">
              <h3>Segmented Lung</h3>
              <img
                src={`data:image/png;base64,${result.segmented_lungs}`}
                alt="Segmented Lung"
                className="result-image"
              />
            </div>

            <div className="image-display-block">
              <h3>Grad-CAM</h3>
              <img
                src={`data:image/png;base64,${result.gradcam_on_segmented}`}
                alt="Grad-CAM Overlay"
                className="result-image"
              />
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default Dashboard;
